# Generated by Django 4.2.9 on 2024-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_createdat_document_modifiedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='src',
            field=models.URLField(default=''),
        ),
    ]
